syntax = "proto3";

package it.lysz210.akasha.capacnan.quipus.credentials;

option java_package = "it.lysz210.akasha.capacnan.quipus.credentials";
option java_multiple_files = true;

import "google/protobuf/timestamp.proto";

message Basic {
  string username = 1;
  string password = 2;
}

message Oauth2Flow {
  string access_token = 1;
  string refresh_token = 2;
  google.protobuf.Timestamp expires_at = 3;
  string token_type = 4; // e.g., "Bearer"
  string scope = 5;
}

message Oauth1Flow {
  string oauth_token = 1;
  string oauth_token_secret = 2;
}

message ApiKey {
  string key = 1;
  string hint = 2; // e.g. "Gemini-Pro-Key"
}