syntax = "proto3";

package it.lysz210.akasha.capacnan.quipus.credentials;

import "security.proto";
import "auth.proto";

option java_package = "it.lysz210.akasha.capacnan.quipus.credentials";
option java_multiple_files = true;

message CredentialQuipu {
  string user_id = 1;
  EncryptionMeta security = 2;

  // Encrypted bytes of the SecretData message
  bytes encrypted_payload = 3;
}

// Should be encrypted
message SecretData {
  string service_id = 1;
  oneof type {
    Oauth2Flow oauth2_flow = 2;
    Oauth1Flow oauth1_flow = 3;
    Basic basic = 4;
    ApiKey api_key = 5;
  }
}