syntax = "proto3";

package it.lysz210.akasha.capacnan.quipus.credentials;

// Imports relative to the root folder
import "security.proto";
import "oauth.proto";
import "static.proto";

option java_package = "it.lysz210.akasha.capacnan.quipus.credentials";
option java_multiple_files = true;

message CredentialEnvelope {
  string user_id = 1;
  EncryptionMeta security = 2;

  // Encrypted bytes of the SecretData message
  bytes encrypted_payload = 3;
}

// This is what you encrypt/decrypt locally
message SecretData {
  oneof type {
    Oauth2Flow strava = 1;
    Oauth1Flow flickr = 2;
    StaticKey gemini = 3;
  }

  // Slot support for your "Dual Login" strategy
  bool is_backup_slot = 4;
}