syntax = "proto3";

package it.lysz210.akasha.capacnan.quipus;

// Imports relative to the root folder
import "common/security.proto";
import "credentials/oauth.proto";
import "credentials/static.proto";

option java_package = "it.lysz210.akasha.capacnan.quipus";
option java_multiple_files = true;

message CredentialEnvelope {
  string user_id = 1;
  common.EncryptionMeta security = 2;
  
  // Encrypted bytes of the SecretData message
  bytes encrypted_payload = 3; 
}

// This is what you encrypt/decrypt locally
message SecretData {
  oneof type {
    credentials.Oauth2Flow strava = 1;
    credentials.Oauth1Flow flickr = 2;
    credentials.StaticKey gemini = 3;
  }
  
  // Slot support for your "Dual Login" strategy
  bool is_backup_slot = 4;
}